FROM php:8.3-fpm

# Install dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    libzip-dev \
    pkg-config \
    git \
    curl \
    zip \
    unzip \
    gnupg \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libfontconfig1 \
    libxrender1 \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) pdo pdo_pgsql gd mbstring dom zlib
    && docker-php-ext-install zip gd pdo pdo_pgsql

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Install Node.js + npm (gunakan versi stabil LTS)
RUN curl -fsSL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -y nodejs && \
    echo "📦 Node.js version:" && node -v && \
    echo "📦 npm version (before update):" && npm -v && \
    npm install -g npm && \
    echo "📦 npm version (after update):" && npm -v && \
    rm nodesource_setup.sh

# Set working directory
WORKDIR /var/www/html

# Tambahkan folder ke daftar aman Git
RUN git config --global --add safe.directory /var/www/html
