FROM php:8.3-fpm

# Install dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    git \
    curl \
    zip \
    unzip \
    gnupg \
    && docker-php-ext-install pdo pdo_pgsql

    
# Install GD dan dependensinya kebutuhan gambar pada generate pdf
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd
    
# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Install Node.js + npm (gunakan versi stabil LTS)
RUN curl -fsSL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -y nodejs && \
    echo "📦 Node.js version:" && node -v && \
    echo "📦 npm version (before update):" && npm -v && \
    npm install -g npm && \
    echo "📦 npm version (after update):" && npm -v && \
    rm nodesource_setup.sh
    
# Set working directory
WORKDIR /var/www/html

# Tambahkan folder ke daftar aman Git
RUN git config --global --add safe.directory /var/www/html