sonar.projectKey=CIVIKA-APP
sonar.projectName=CIVIKA APP
sonar.projectVersion=1.0
sonar.sources=app,resources,config,routes
sonar.exclusions=vendor/,storage/,public/,tests/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://172.17.0.2:9000
sonar.token=sqa_bff96b81128c28331d7bb38b2d265c375f552ac8
